/**
 * Victorian Lingo — Core Data Models
 *
 * TypeScript interfaces for all domain entities used across services,
 * stores, and UI components.
 */

// ── Gutendex API Response Types ──────────────────────────────────────────────

export interface GutendexAuthor {
  name: string;
  birth_year: number | null;
  death_year: number | null;
}

export interface GutendexFormat {
  [mimeType: string]: string; // mime -> URL
}

export interface GutendexBook {
  id: number;
  title: string;
  authors: GutendexAuthor[];
  subjects: string[];
  bookshelves: string[];
  languages: string[];
  copyright: boolean | null;
  media_type: string;
  formats: GutendexFormat;
  download_count: number;
  summaries?: string[];
}

export interface GutendexResponse {
  count: number;
  next: string | null;
  previous: string | null;
  results: GutendexBook[];
}

// ── Domain: Book ─────────────────────────────────────────────────────────────

export type ReadingDifficulty = 'Easy' | 'Moderate' | 'Demanding';

export interface Book {
  id: string;                       // internal UUID
  gutenbergId: number;
  title: string;
  author: string;                   // primary author display name
  authorBirthYear: number | null;
  authorDeathYear: number | null;
  subjects: string[];
  bookshelves: string[];
  synopsis: string | null;          // from Gutenberg summary or truncated text
  publicationYear: number | null;   // derived from subjects / author dates
  difficulty: ReadingDifficulty | null;
  cachedTextPath: string | null;    // local file path after download
  isDownloaded: boolean;
  readProgress: number;             // 0–1
  lastReadAt: string | null;        // ISO 8601
  addedAt: string;                  // ISO 8601
  coverColor: string;               // derived accent color for card display
}

export type BookSummary = Pick<
  Book,
  'id' | 'gutenbergId' | 'title' | 'author' | 'difficulty' | 'isDownloaded' | 'readProgress' | 'coverColor'
>;

// ── Domain: Vocabulary ────────────────────────────────────────────────────────

export type VocabCategory = 'Archaic' | 'PeriodSlang' | 'FalseFriend';

export interface VocabWord {
  id: string;
  word: string;
  partOfSpeech: string;             // noun, verb, adjective, etc.
  phonetic: string | null;
  categoryLabel: VocabCategory;
  categoryNote: string;             // one-sentence explanation of the label
  eraDefinition: string;            // Victorian/Regency period definition
  modernDefinition: string | null;  // modern definition if it differs
  exampleSentence: string;          // real sentence from the corpus
  bookId: string | null;            // null = standalone (Word of the Era, etc.)
  bookTitle: string | null;
  savedAt: string;                  // ISO 8601
  isSaved: boolean;                 // whether user saved to notebook
  tags: string[];
}

export interface EtymologyStep {
  language: string;                 // e.g. "Latin", "Old French"
  form: string;                     // the word in that language
  translation: string;              // meaning in that language
  century: string | null;           // e.g. "14th century"
}

export interface Etymology {
  wordId: string;
  chain: EtymologyStep[];
  relatedWords: string[];           // other English words from the same root
}

// ── Domain: Quote ─────────────────────────────────────────────────────────────

export interface SavedQuote {
  id: string;
  text: string;
  bookId: string;
  bookTitle: string;
  author: string;
  chapter: string | null;
  charOffset: number;               // character position in text for resume
  savedAt: string;                  // ISO 8601
  tags: string[];
}

// ── Domain: Flashcard & Spaced Repetition ─────────────────────────────────────

export type QuizDifficulty = 'Easy' | 'OK' | 'Hard';

export interface FlashcardReview {
  id: string;
  vocabWordId: string;
  reviewedAt: string;               // ISO 8601
  difficulty: QuizDifficulty;
  intervalDays: number;             // SM-2 interval
  easeFactor: number;               // SM-2 ease factor (starts at 2.5)
  dueAt: string;                    // ISO 8601 next review date
  reviewCount: number;
  accuracyRate: number;             // 0–1
}

export interface FlashcardDeck {
  id: string;
  name: string;
  bookId: string | null;            // null = custom deck
  wordIds: string[];
  createdAt: string;
  isAutoGenerated: boolean;
}

// ── Domain: Quiz ──────────────────────────────────────────────────────────────

export type QuizFormat =
  | 'DefinitionMatch'
  | 'WordFromDefinition'
  | 'FillInBlank'
  | 'OddOneOut';

export interface QuizQuestion {
  id: string;
  format: QuizFormat;
  prompt: string;                   // the question text or sentence
  options: string[];                // 4 options
  correctIndex: number;             // index of correct option in options[]
  vocabWordId: string | null;       // null for OddOneOut
  explanation: string;              // shown after answering
}

export interface QuizSession {
  id: string;
  deckId: string;
  format: QuizFormat;
  questions: QuizQuestion[];
  answers: (number | null)[];       // user's answer per question
  startedAt: string;
  completedAt: string | null;
  score: number | null;             // 0–1
}

// ── Domain: Progress & Achievements ──────────────────────────────────────────

export interface ReadingSession {
  id: string;
  bookId: string;
  durationSeconds: number;
  date: string;                     // YYYY-MM-DD
}

export interface Achievement {
  id: string;
  type: AchievementType;
  earnedAt: string;                 // ISO 8601
}

export type AchievementType =
  | 'FirstBook'
  | 'FiveBooks'
  | 'TenBooks'
  | 'FiftyWords'
  | 'TwoHundredWords'
  | 'SevenDayStreak'
  | 'ThirtyDayStreak'
  | 'FirstQuiz'
  | 'PerfectQuiz'
  | 'FirstQuote'
  | 'CommonplaceBook'; // 20+ saved quotes

export const AchievementMeta: Record<AchievementType, { title: string; description: string; icon: string }> = {
  FirstBook:         { title: 'The First Chapter',         description: 'Completed your first book',                  icon: '📖' },
  FiveBooks:         { title: 'Member of the Lending Library', description: 'Completed five books',                   icon: '🏛️' },
  TenBooks:          { title: 'Fellow of the Gothic Society', description: 'Completed ten books',                     icon: '🦇' },
  FiftyWords:        { title: 'Keeper of the Commonplace Book', description: 'Saved fifty words to the Notebook',    icon: '✒️' },
  TwoHundredWords:   { title: 'Order of the Inkwell',      description: 'Saved two hundred words',                   icon: '🖋️' },
  SevenDayStreak:    { title: 'Seven Sennight',            description: 'Read every day for a week',                  icon: '🕯️' },
  ThirtyDayStreak:   { title: 'The Diligent Scholar',      description: 'Read every day for a month',                icon: '🎖️' },
  FirstQuiz:         { title: 'The Examination',           description: 'Completed your first quiz',                  icon: '📜' },
  PerfectQuiz:       { title: 'With Distinction',          description: 'Achieved a perfect quiz score',              icon: '🌟' },
  FirstQuote:        { title: 'The Quotable Reader',       description: 'Saved your first quote',                     icon: '❝' },
  CommonplaceBook:   { title: 'Commonplace Book Filled',   description: 'Saved twenty or more quotes',                icon: '📕' },
};

// ── Domain: User Settings ─────────────────────────────────────────────────────

export type ReadingModeKey = 'parchment' | 'sepia' | 'candlelight' | 'midnight';

export interface UserSettings {
  readingMode: ReadingModeKey;
  fontSize: number;                 // e.g. 17 (matches FontSize.body)
  showVocabHighlights: boolean;
  soundEnabled: boolean;
  reduceMotion: boolean;
}

export const DefaultSettings: UserSettings = {
  readingMode: 'parchment',
  fontSize: 17,
  showVocabHighlights: true,
  soundEnabled: false,
  reduceMotion: false,
};
